### ISSUE TITLE
Add "Alternate Programs" to the "Degree Programs" page

### ISSUE THREAD

**Issue by ElliotFriend** [stlchristian/stlchristian.edu#56]
I've got the bulk of this done. Haley has also written and submitted the various program pages. What remains to be done is to display them properly. As it is, the view wants to place "Alternate Programs" as the first set of degrees. We want it at the end. Maybe a sorting issue?

**Comment by ElliotFriend** [comment]
@hwomble [Check it out](https://stlchristian.edu/academics/degree-programs)

Now, I need you to come up with a one- or two-sentence description of these "alternate programs." Just like where we have:

>Our **traditional degree programs** have classes which meet during the daytime, and are geared toward students looking for the "traditional" college experience.
>
>Our **evening degree programs** make it easy for you to take advantage of learning from a professor in-person while allowing you to continue meeting your family and work needs.
>
>Our **online degree programs** are ideal for distance learners and those who are looking to work at a more individualized pace.

Also, what are your thoughts on changing "Alternate Programs" to "Alternative Programs"? There is very little difference, I'm aware. But, for some reason, I like the longer word. Thoughts?

**Comment by hwomble** [comment]
Our Certificate Program functions as a low-cost alternative to receiving a degree. Our Certificates are designed for our non-degree seeking students who desire to learn biblical knowledge and/or Christian leadership at a fraction of the cost.

Does that sound OK?
And I'm ok with "Alternative Programs" - I think either sounds fine, so if you're drawn more to the longer word, it's fine with me :)
